name: Tag Docker Image with Git

on:
  push:
    tags: ['*']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: techwolf12/pocketbase

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log into the Container registry
      uses: docker/login-action@3d100841f68d4548bf57e52eb27bd33ec5069f55
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for the Docker image
      id: meta
      uses: docker/metadata-action@032a4b3bda1b716928481836ac5bfe36e1feaad6
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
